### ISSUE TITLE
Language distribution

### ISSUE THREAD

**Issue by hbredin** [X-LANCE/MSDWILD#1]
Thanks for this dataset: a very valuable contribution to the speaker diarization community! 

Paper (Section 3, Stage 1) says  

> To improve the language diversity, we change the website location or use Google Translate to translate those English keywords into different languages such as Chinese, Thai, Korean, Japanese, German, Portuguese, and Arabic.

Therefore, it sounds like MSDWild is one of the few publicly available speaker diarization datasets to actually be multi-lingual. Do you have any estimation of the distribution of languages in MSDWild that you could share?

**Comment by liutaocode** [comment]
![image](https://github.com/X-LANCE/MSDWILD/assets/91858374/25a73e40-084d-4f81-b8a9-0c67bad6b499)


Hello. My apologies for the late reply. When we initially collected the data, we did some statistical analysis on its distribution. This table presents the distribution statistics: some of the data was extracted from the video's meta information, while some were annotated by our tagging team. Nonetheless, we believe that the current trends across the dataset remain consistent.

**Comment by hbredin** [comment]
Thanks a lot! Better later than never 👍

**Comment by liutaocode** [comment]
Thank you for your question. If you have any further questions, please feel free to open a new issue.
