### ISSUE TITLE
Did you try any experiments detecting off-screen speech when using Visual-audio pipeline manner?

### ISSUE THREAD

**Issue by msp3887** [X-LANCE/MSDWILD#2]
Thanks for providing great Multi-Modal Speaker Diarization Dataset.
I read the paper 'MSDWILD: MULTI-MODAL SPEAKER DIARIZATION DATASET IN THE WILD' and try to execute TalkNet-ASD model for Audio-Visual diarization result.
I think TalkNet model is useful when on-screen situation.
However, It looks like that TalkNet-ASD model would not be able to detect speech when off-screen situations and audio-only diarization result would be needed for detecting off-screen situations.

**Comment by liutaocode** [comment]
Hello. Thank you for your interest in our work. While the off-screen audio is annotated in our dataset, the algorithms used in this article (including TalkNet) do not handle off-screen audio. TalkNet can only handle situations with visual input. Additionally, according to our statistics, off-screen audio constitutes only a very small portion of the dataset we crawled (speaker parts annotated with "h" in rttm). Therefore, we have not considered off-screen audio in this study. However, handling off-screen audio is indeed a topic worthy of further research.

**Comment by msp3887** [comment]
Thank you for your opinion😀
